### ISSUE TITLE
Parse Error with specific User Names

### ISSUE THREAD

**Issue by davglass** [gf3/Jerk#6]
This is probably an issue with IRC-JS, but it may be an issue with Jerk.

If I have a bot in a room and someone with a username like this: davglass\test` joins, it throws a syntax error:

[Thu, 20 Jan 2011 15:31:24 GMT] ERROR      [ERROR] Failed parsing ':davglass\test`!~davglass@173-27-206-95.client.mchsi.com JOIN :#yui'

/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/irc.js:136
          throw err
          ^
Error: treeWalker: parse failed: 0 parse already failed
    at err (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/node_modules/PanPG/PanPG_util.js:157:9)
    at Object.treeWalker (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/node_modules/PanPG/PanPG_util.js:104:10)
    at Object.walk (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/walker.js:36:21)
    at Object.compile (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/compiler.js:8:17)
    at IRC.parseMessage (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/irc.js:116:28)
    at Stream.<anonymous> (native)
    at Stream.emit (events:27:15)
    at IOWatcher.callback (net:484:33)
    at node.js:773:9

I can stop this by setting options.log: false in the config, but that doesn't help me since I like my logging.

**Comment by gf3** [comment]
Commented on the IRC-js issue:

https://github.com/gf3/IRC-js/issues/issue/18
